name: gphase
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11.11
  - pip=25.0

  # Python dependencies used by GPhase + submodules
  - numpy=1.26.4
  - pandas=2.2.3
  - scipy=1.15.1
  - scikit-learn=1.6.1
  - statsmodels=0.14.4
  - matplotlib-base=3.10.0
  - networkx=3.4.2
  - networkit=11.1.post1
  - python-igraph=0.10.4
  - igraph=0.10.15
  - pysam=0.22.1
  - biopython=1.78
  - argcomplete=3.5.3
  - kneed=0.8.5
  - python-louvain=0.16
  - portion=2.6.0
  - sortedcontainers=2.4.0
  - pathos=0.3.3

  # popCNV GUI (optional, but bundled in this repo)
  #- pyside6=6.7.2

  # External tools called by pipeline scripts
  - samtools=1.21
  - minimap2=2.28
  - mosdepth=0.3.10
  - chromap=0.2.7
  - seqkit=2.9.0
  - yahs=1.2.2
  - openjdk=17
  - bc
  - gawk
  - coreutils
  - util-linux

  - pip:
      - bio-agptools==0.0.3
